"""Schema migration for AgentBase SQLite database."""

from __future__ import annotations

import logging

import aiosqlite

from ..exceptions import StorageError

logger = logging.getLogger(__name__)

# Current schema version
CURRENT_VERSION = 1

# ---------------------------------------------------------------------------
# Schema DDL statements — ordered by dependency
# ---------------------------------------------------------------------------

_SCHEMA_V1_STATEMENTS = [
    # --- Main context table ---
    """CREATE TABLE IF NOT EXISTS context_entries (
        id              TEXT PRIMARY KEY,
        context_type    TEXT NOT NULL DEFAULT 'memory',
        memory_category TEXT,
        status          TEXT NOT NULL DEFAULT 'pending',
        origin_type     TEXT NOT NULL DEFAULT 'manual',
        origin_id       TEXT,
        l0_abstract     TEXT NOT NULL DEFAULT '',
        l1_overview     TEXT NOT NULL DEFAULT '',
        l2_full         TEXT NOT NULL DEFAULT '',
        fts_text        TEXT NOT NULL DEFAULT '',
        embedding_hash          TEXT NOT NULL DEFAULT '',
        embedding_source_level  TEXT NOT NULL DEFAULT 'l1',
        embedding_model         TEXT,
        embedding_dimensions    INTEGER,
        scope           TEXT NOT NULL DEFAULT 'global',
        owner_id        TEXT,
        tags            TEXT NOT NULL DEFAULT '[]',
        confidence      REAL NOT NULL DEFAULT 1.0,
        source          TEXT NOT NULL DEFAULT 'unknown',
        uri             TEXT NOT NULL DEFAULT '',
        resource_url    TEXT,
        resource_format TEXT,
        resource_size   INTEGER,
        skill_tool_name TEXT,
        skill_api_spec  TEXT,
        valid_from      TEXT NOT NULL,
        valid_until     TEXT,
        superseded_by   TEXT,
        created_at      TEXT NOT NULL,
        updated_at      TEXT NOT NULL,
        deleted_at      TEXT,
        extra           TEXT NOT NULL DEFAULT '{}',
        CHECK (context_type IN ('memory','resource','skill')),
        CHECK (status IN ('pending','active','superseded','archived','deleted','failed')),
        CHECK (origin_type IN ('manual','session','import','extracted','generated','synced')),
        CHECK (confidence >= 0.0 AND confidence <= 1.0),
        CHECK (scope IN ('global','agent','project','session')),
        CHECK (scope != 'global' OR owner_id IS NULL)
    )""",

    # --- Context entry indexes ---
    "CREATE INDEX IF NOT EXISTS idx_ctx_scope ON context_entries(scope, owner_id)",
    "CREATE INDEX IF NOT EXISTS idx_ctx_type ON context_entries(context_type)",
    "CREATE INDEX IF NOT EXISTS idx_ctx_status ON context_entries(status)",
    "CREATE INDEX IF NOT EXISTS idx_ctx_origin ON context_entries(origin_type, origin_id)",
    "CREATE INDEX IF NOT EXISTS idx_ctx_source ON context_entries(source)",
    "CREATE INDEX IF NOT EXISTS idx_ctx_valid ON context_entries(valid_from, valid_until)",
    "CREATE INDEX IF NOT EXISTS idx_ctx_created ON context_entries(created_at)",
    "CREATE INDEX IF NOT EXISTS idx_ctx_uri ON context_entries(uri)",

    # --- FTS5 virtual table ---
    # Indexes fts_text (tokenized) instead of l2_full (raw) for CJK support.
    # l0_abstract and l1_overview are kept as-is since they are typically
    # short English summaries generated by LLM.
    """CREATE VIRTUAL TABLE IF NOT EXISTS context_fts USING fts5(
        l0_abstract,
        l1_overview,
        fts_text,
        tags,
        content=context_entries,
        content_rowid=rowid,
        tokenize='unicode61'
    )""",

    # --- FTS5 triggers ---
    """CREATE TRIGGER IF NOT EXISTS ctx_ai AFTER INSERT ON context_entries BEGIN
        INSERT INTO context_fts(rowid, l0_abstract, l1_overview, fts_text, tags)
        VALUES (new.rowid, new.l0_abstract, new.l1_overview, new.fts_text, new.tags);
    END""",
    
    """CREATE TRIGGER IF NOT EXISTS ctx_ad AFTER DELETE ON context_entries BEGIN
        INSERT INTO context_fts(context_fts, rowid, l0_abstract, l1_overview, fts_text, tags)
        VALUES ('delete', old.rowid, old.l0_abstract, old.l1_overview, old.fts_text, old.tags);
    END""",
    
    """CREATE TRIGGER IF NOT EXISTS ctx_au AFTER UPDATE ON context_entries BEGIN
        INSERT INTO context_fts(context_fts, rowid, l0_abstract, l1_overview, fts_text, tags)
        VALUES ('delete', old.rowid, old.l0_abstract, old.l1_overview, old.fts_text, old.tags);
        INSERT INTO context_fts(rowid, l0_abstract, l1_overview, fts_text, tags)
        VALUES (new.rowid, new.l0_abstract, new.l1_overview, new.fts_text, new.tags);
    END""",

    # --- Context tags (high-frequency filter helper) ---
    """CREATE TABLE IF NOT EXISTS context_tags (
        context_id TEXT NOT NULL REFERENCES context_entries(id) ON DELETE CASCADE,
        tag        TEXT NOT NULL
    )""",
    "CREATE INDEX IF NOT EXISTS idx_ctx_tag ON context_tags(tag)",
    "CREATE INDEX IF NOT EXISTS idx_ctx_tag_context ON context_tags(context_id)",
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_ctx_tag_unique ON context_tags(context_id, tag)",

    # --- Entities ---
    """CREATE TABLE IF NOT EXISTS entities (
        id          TEXT PRIMARY KEY,
        name        TEXT NOT NULL,
        entity_type TEXT NOT NULL,
        description TEXT NOT NULL DEFAULT '',
        first_seen  TEXT NOT NULL,
        last_seen   TEXT NOT NULL,
        fact_count  INTEGER NOT NULL DEFAULT 0,
        properties  TEXT NOT NULL DEFAULT '{}',
        created_at  TEXT NOT NULL,
        updated_at  TEXT NOT NULL
    )""",
    "CREATE INDEX IF NOT EXISTS idx_entity_name ON entities(name)",
    "CREATE INDEX IF NOT EXISTS idx_entity_type ON entities(entity_type)",
    "CREATE INDEX IF NOT EXISTS idx_entity_last_seen ON entities(last_seen)",

    # --- Entity aliases ---
    """CREATE TABLE IF NOT EXISTS entity_aliases (
        entity_id TEXT NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
        alias     TEXT NOT NULL
    )""",
    "CREATE INDEX IF NOT EXISTS idx_entity_alias ON entity_aliases(alias)",
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_entity_alias_unique ON entity_aliases(entity_id, alias)",

    # --- Relations ---
    """CREATE TABLE IF NOT EXISTS relations (
        id          TEXT PRIMARY KEY,
        source_id   TEXT NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
        target_id   TEXT NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
        predicate   TEXT NOT NULL,
        valid_from  TEXT NOT NULL,
        valid_until TEXT,
        confidence  REAL NOT NULL DEFAULT 1.0,
        evidence_ids TEXT NOT NULL DEFAULT '[]',
        properties  TEXT NOT NULL DEFAULT '{}',
        created_at  TEXT NOT NULL,
        updated_at  TEXT NOT NULL
    )""",
    "CREATE INDEX IF NOT EXISTS idx_rel_source ON relations(source_id, valid_until)",
    "CREATE INDEX IF NOT EXISTS idx_rel_target ON relations(target_id, valid_until)",
    "CREATE INDEX IF NOT EXISTS idx_rel_predicate ON relations(predicate)",
    "CREATE INDEX IF NOT EXISTS idx_rel_valid ON relations(valid_from, valid_until)",
    "CREATE INDEX IF NOT EXISTS idx_rel_source_pred ON relations(source_id, predicate, valid_until)",

    # --- Fact timeline ---
    """CREATE TABLE IF NOT EXISTS fact_timeline (
        id              TEXT PRIMARY KEY,
        entity_id       TEXT NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
        fact            TEXT NOT NULL,
        valid_at        TEXT NOT NULL,
        superseded_by   TEXT,
        action          TEXT NOT NULL DEFAULT 'created',
        created_at      TEXT NOT NULL
    )""",
    "CREATE INDEX IF NOT EXISTS idx_fact_entity ON fact_timeline(entity_id, valid_at)",
    "CREATE INDEX IF NOT EXISTS idx_fact_superseded ON fact_timeline(superseded_by)",

    # --- Context-Entity links ---
    """CREATE TABLE IF NOT EXISTS context_entity_links (
        context_id  TEXT NOT NULL REFERENCES context_entries(id) ON DELETE CASCADE,
        entity_id   TEXT NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
        role        TEXT,
        confidence  REAL NOT NULL DEFAULT 1.0
    )""",
    "CREATE INDEX IF NOT EXISTS idx_cel_context ON context_entity_links(context_id)",
    "CREATE INDEX IF NOT EXISTS idx_cel_entity ON context_entity_links(entity_id)",

    # --- Sessions ---
    """CREATE TABLE IF NOT EXISTS sessions (
        id                      TEXT PRIMARY KEY,
        agent_id                TEXT NOT NULL DEFAULT 'default',
        project                 TEXT,
        status                  TEXT NOT NULL DEFAULT 'active',
        archived_summary_l0     TEXT NOT NULL DEFAULT '',
        archived_summary_l1     TEXT NOT NULL DEFAULT '',
        archived_message_count  INTEGER NOT NULL DEFAULT 0,
        total_tokens_used       INTEGER NOT NULL DEFAULT 0,
        extracted_memory_ids    TEXT NOT NULL DEFAULT '[]',
        created_at              TEXT NOT NULL,
        updated_at              TEXT NOT NULL,
        committed_at            TEXT
    )""",
    "CREATE INDEX IF NOT EXISTS idx_session_agent ON sessions(agent_id, status)",
    "CREATE INDEX IF NOT EXISTS idx_session_project ON sessions(project, status)",
    "CREATE INDEX IF NOT EXISTS idx_session_status ON sessions(status)",

    # --- Session messages ---
    """CREATE TABLE IF NOT EXISTS session_messages (
        id              TEXT PRIMARY KEY,
        session_id      TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
        role            TEXT NOT NULL,
        content         TEXT NOT NULL,
        tool_call_id    TEXT,
        tool_name       TEXT,
        token_count     INTEGER NOT NULL DEFAULT 0,
        created_at      TEXT NOT NULL
    )""",
    "CREATE INDEX IF NOT EXISTS idx_msg_session ON session_messages(session_id, created_at)",

    # --- Session-Memory links ---
    """CREATE TABLE IF NOT EXISTS session_memory_links (
        session_id  TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
        context_id  TEXT NOT NULL REFERENCES context_entries(id) ON DELETE CASCADE
    )""",
    "CREATE INDEX IF NOT EXISTS idx_sml_session ON session_memory_links(session_id)",
    "CREATE INDEX IF NOT EXISTS idx_sml_context ON session_memory_links(context_id)",

    # --- Retrieval traces ---
    """CREATE TABLE IF NOT EXISTS retrieval_traces (
        id                  TEXT PRIMARY KEY,
        query               TEXT NOT NULL,
        strategy            TEXT NOT NULL DEFAULT 'hybrid',
        steps               TEXT NOT NULL DEFAULT '[]',
        result_ids          TEXT NOT NULL DEFAULT '[]',
        total_latency_ms    REAL NOT NULL DEFAULT 0.0,
        token_budget_used   INTEGER NOT NULL DEFAULT 0,
        token_budget_limit  INTEGER NOT NULL DEFAULT 0,
        created_at          TEXT NOT NULL
    )""",
    "CREATE INDEX IF NOT EXISTS idx_trace_created ON retrieval_traces(created_at)",

    # --- Trace steps ---
    """CREATE TABLE IF NOT EXISTS trace_steps (
        trace_id    TEXT NOT NULL REFERENCES retrieval_traces(id) ON DELETE CASCADE,
        step_order  INTEGER NOT NULL,
        step_name   TEXT NOT NULL,
        started_at  TEXT,
        finished_at TEXT,
        latency_ms  REAL,
        input_count INTEGER DEFAULT 0,
        output_count INTEGER DEFAULT 0,
        model_name  TEXT,
        cache_hit   INTEGER DEFAULT 0,
        error_code  TEXT,
        budget_before INTEGER,
        budget_after  INTEGER
    )""",
    "CREATE INDEX IF NOT EXISTS idx_trace_step ON trace_steps(trace_id, step_order)",

    # --- Embedding cache ---
    """CREATE TABLE IF NOT EXISTS embedding_cache (
        content_hash TEXT PRIMARY KEY,
        embedding    BLOB NOT NULL,
        model        TEXT NOT NULL,
        dimensions   INTEGER NOT NULL,
        created_at   TEXT NOT NULL
    )""",
    "CREATE INDEX IF NOT EXISTS idx_cache_model ON embedding_cache(model)",

    # --- Background jobs ---
    """CREATE TABLE IF NOT EXISTS background_jobs (
        id           TEXT PRIMARY KEY,
        job_type     TEXT NOT NULL,
        payload      TEXT,
        status       TEXT NOT NULL DEFAULT 'pending',
        attempts     INTEGER NOT NULL DEFAULT 0,
        max_attempts INTEGER NOT NULL DEFAULT 3,
        error_message TEXT,
        created_at   TEXT NOT NULL,
        started_at   TEXT,
        completed_at TEXT
    )""",
    "CREATE INDEX IF NOT EXISTS idx_job_status ON background_jobs(status, job_type)",
    "CREATE INDEX IF NOT EXISTS idx_job_type ON background_jobs(job_type, status)",

    # --- Vec metadata (for sqlite-vec, created even if vec extension not loaded) ---
    """CREATE TABLE IF NOT EXISTS vec_meta (
        rowid         INTEGER PRIMARY KEY AUTOINCREMENT,
        context_id    TEXT NOT NULL UNIQUE,
        context_type  TEXT NOT NULL,
        scope         TEXT NOT NULL,
        owner_id      TEXT,
        confidence    REAL NOT NULL DEFAULT 1.0
    )""",

    # --- Schema version ---
    """CREATE TABLE IF NOT EXISTS schema_version (
        version     INTEGER PRIMARY KEY,
        description TEXT NOT NULL,
        applied_at  TEXT NOT NULL
    )""",
]


class Migrator:
    """Schema migration manager."""

    def __init__(self, conn: aiosqlite.Connection) -> None:
        self._conn = conn

    async def current_version(self) -> int:
        """Get the current schema version."""
        try:
            cursor = await self._conn.execute(
                "SELECT MAX(version) FROM schema_version"
            )
            row = await cursor.fetchone()
            return row[0] if row and row[0] is not None else 0
        except aiosqlite.OperationalError:
            return 0

    async def migrate(self) -> None:
        """Run all pending migrations."""
        version = await self.current_version()

        if version < 1:
            await self._migrate_v1()

        logger.info(f"Schema migration complete: version {await self.current_version()}")

    async def _migrate_v1(self) -> None:
        """Apply V1 schema."""
        for stmt in _SCHEMA_V1_STATEMENTS:
            try:
                await self._conn.execute(stmt)
            except aiosqlite.OperationalError as e:
                # Ignore "already exists" errors for idempotent migrations
                if "already exists" not in str(e).lower():
                    raise StorageError(f"Schema V1 migration failed: {e}") from e

        await self._conn.execute(
            "INSERT INTO schema_version (version, description, applied_at) VALUES (?, ?, datetime('now'))",
            (1, "Initial schema"),
        )
        await self._conn.commit()
